### ISSUE TITLE
Cannot get build

### ISSUE THREAD

**Issue by ahmetteksas** [forcepusher/com.bananaparty.yandexgames#2]
Hello dear, I cannot get webgl built after import your sdk to the project. Unity version is 2022.3.4f. What could be the issue? Error line is below; 

Build completed with a result of 'Failed' in 486 seconds (486399 ms) Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output: Traceback (most recent call last): File "C:\Program Files\Unity\Hub\Editor\2022.3.4f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\\emcc.py", line 3982, in <module>

**Comment by ahmetteksas** [comment]
Could you please solve the issue? I think it s about some DLL functions

**Comment by forcepusher** [comment]
Hello. I'm afraid this has nothing to do with the SDK. Sorry.
