### ISSUE TITLE
Новый лоадер

### ISSUE THREAD

**Issue by und3rd0gg** [forcepusher/com.bananaparty.yandexgames#6]
@forcepusher Привет, там яндекс выкатили какой то новый лоадер, и теперь со старым они не пропускают, если используешь геймреди. Могу я попросить добавить новый лоадер?
![image](https://github.com/user-attachments/assets/332a4ad9-75ba-43f6-a857-0e86ea7567b8)

**Comment by forcepusher** [comment]
Та он теперь ваще ничё загрузить не даёт. Такое чувство что пора сворачиваться.
![image](https://github.com/user-attachments/assets/a7af736f-3d60-4611-97ab-66b0cf877739)

**Comment by forcepusher** [comment]
Вообще никак, даже это для теста в HTML добавил, и чё они сломали понятия не имею
```
<!-- Yandex Games SDK -->
<script src="https://sdk.games.s3.yandex.net/sdk.js"></script>
```

**Comment by forcepusher** [comment]
Так, косяк с заливкой решил. Надо было включить Decompression Fallback и поставить любой Compression Format кроме None.
![image](https://github.com/user-attachments/assets/1ed16daa-6402-4cba-a982-d9a3b31e9b00)

**Comment by forcepusher** [comment]
Лол кек чебурек. Не даёт загрузить скрипт своего же SDK.
![image](https://github.com/user-attachments/assets/2e666b83-8311-401b-96e2-373acac5d602)

**Comment by forcepusher** [comment]
Написал в саппорт, это может подзатянуться

**Comment by forcepusher** [comment]
А так надо было подключать не `https://sdk.games.s3.yandex.net/sdk.js` а просто `/sdk.js`
Теперь всё робит, апдейт пилю

**Comment by forcepusher** [comment]
Выкатил в 16.1.1
`https://github.com/forcepusher/com.agava.yandexgames.git#16.1.1`

**Comment by und3rd0gg** [comment]
спасибо огромное! ❤️
